### ISSUE TITLE
Migration for PostgreSQL is not correct

### ISSUE THREAD

**Issue by alexqrid** [ava-labs/ortelius#201]
[Migrations](https://github.com/ava-labs/ortelius/tree/master/services/db/migrations) are not suitable for PostgreSQL, because of different types. For example, there is no `varbinary` or `smallint/bigint unsigned`  data types in PostgreSQL. It should be corrected in order to work corretly with PostgreSQL.

**Comment by tasinco** [comment]
Since we have uint64 types we must index from the node transaction types.  The need to use unsigned bigint is imperative...  A bigint in postgres would never hold the value..

Converting to decimals would be a big undertaking (possibly a re-write), and is not slated any time soon.

Amazon aws offers an aurora database which offers mysql connections with a custom db backend.  That could be a workable solution.

At this time we will not be able to support postgres.

**Comment by alexqrid** [comment]
Ok, then it's better to update the docs and remove `postgres` from it.
