### ISSUE TITLE
Everest: duplicated txs

### ISSUE THREAD

**Issue by menxit** [ava-labs/ortelius#36]
Ortelius returns duplicated txs on asset detail:
- https://explorerapi.avax.network/x/transactions?assetID=nznftJBicce1PfWQeNEVBmDyweZZ6zcM3p78z9Hy9Hhdhfaxm
- https://explorer.avax.network/asset/nznftJBicce1PfWQeNEVBmDyweZZ6zcM3p78z9Hy9Hhdhfaxm

**Comment by tyler-smith** [comment]
The cause of this issue is a faulty JOIN when filtering transactions by asset and/or address.

## Relevant schema:
```
Transactions has many Outputs
Outputs has many OutputAddresses.

Outputs has asset_id property
OutputAddresses has address property 
```

## Bug analysis:
We JOIN Outputs and OutputAddresses to Transactions to enable a WHERE clause restricting asset_id and/or address, so transactions with multiple outputs or multiple addresses on an output  become duplicated.

Code: https://github.com/ava-labs/ortelius/blob/40ca1f3237a5914f1417c0bf8a342aab66e77113/services/indexes/avm/params.go#L202-L214
